### ISSUE TITLE
Where to find the original linter source file

### ISSUE THREAD

**Issue by jasjuang** [Pendrokar/SublimeLinter-contrib-csharplint#3]
Excuse my ignorance, I have unity installed and SublimeLinter-contrib-csharplint but I think I am missing a connection somewhere for this to work. I cannot find anything like csharplint.exe anywhere. Could you give me a more detailed explanation on  how to get it to work?

**Comment by Pendrokar** [comment]
Yeah, just as I mention there is no actual linter named charplint, I simply use the Mono compiler to check errors. I don't know how you need to proceed if you want to use the Windows .NET framework. But here is what you need to look at within the linter.py file:

```
    base_cmd = (
        "mcs "
        " *"
        " -target:library"
        " -out:/tmp/errorcheck.dll"
        #" -out:stdout" doesn't work like that
        #" sdk:3.5" # Unity uses .NET 3.5
        #" -r:./*.dll" # Recursively add all libraries within the folder of file
    )
```

**Comment by jasjuang** [comment]
Sorry I still couldn't find where this linter.py file is located. Is this part of SublimeLinter? or is it part of Mono? And where should I add the base_cmd paragraph to?

For some reason I couldn't install Mono successfully when I download from http://www.mono-project.com/download/.

**Comment by Pendrokar** [comment]
linter.py file is part of the Sublime Package of this repository:
https://github.com/Pendrokar/SublimeLinter-contrib-csharplint/blob/master/linter.py

And if you are trying now to install Mono, then I have no idea what you are using to write your C# scripts. Are you using Visual Studio or Unity 3D game engine? I mention Unity, because that was my personal target. Unity comes with its own Mono installation, but before that I used a separately installed Mono version.

I have not programmed in Visual Studio to be of any help to you, but I doubt you need a Mono installation, as VS C# is not that compatible with Mono C#.

**Comment by jasjuang** [comment]
I am using Unity 3D game engine and have the latest one installed in the
default path.

What I did step by step is

Open Sublime
Ctrl+shift+p
package control: add repository
copy paste the link of this repo
package control: install packages
choose SublimeLinter-contrib-csharplint

Is there anymore need to do?

Up to this point it seems that my .cs file is not being linted

Appreciate your help.

**Comment by Pendrokar** [comment]
Locate "gmcs"("gmcs.bat" for Windows) within the installed Unity directory. Now either change "mcs" to the full path of that executable or add it to the global PATH. Here is how I have that part set up:

```
base_cmd = (
        "\"C:/Program Files/Unity/Editor/Data/Mono/bin/gmcs.bat\" "
        " *"
        " -target:library"
        #" sdk:3.5" # Unity 4/5 uses .NET 2/3.5 # Using gmcs as that will automatically target 3.5
        #" -r:./*.dll" # Recursively add all libraries within the folder of file
)
```

...

Oh wait, there is more. Something that I haven't included anywhere in this repository. The libraries that the executable has to parse the files with. I simply use the ones from the CompleteSharp autocompletion project. Here is the part within my Sublime Text project settings(Project -> Edit Project):

```
    "settings": {
        "completesharp_assemblies": [

            // Unity Editor dlls

            "C:\\Program Files\\Unity\\Editor\\Data\\Managed\\UnityEngine.dll",

            "C:\\Program Files\\Unity\\Editor\\Data\\Managed\\UnityEditor.dll",

            "C:\\Program Files\\Unity\\Editor\\Data\\Mono\\lib\\mono\\unity\\UnityScript.dll",

            "C:\\Program Files\\Unity\\Editor\\Data\\Mono\\lib\\mono\\unity\\System.Core.dll",

            "C:\\Program Files\\Unity\\Editor\\Data\\Mono\\lib\\mono\\unity\\System.dll",

            "C:\\Program Files\\Unity\\Editor\\Data\\Managed\\nunit.framework.dll",

            "C:\\Program Files\\Unity\\Editor\\Data\\Mono\\lib\\mono\\unity\\mscorlib.dll",

            "${project_path:Library}\\ScriptAssemblies\\Assembly-CSharp.dll",

            "${project_path:Library}\\ScriptAssemblies\\Assembly-CSharp-Editor.dll",

            "${project_path:Library}\\ScriptAssemblies\\Assembly-UnityScript.dll",

            "${project_path:Library}\\ScriptAssemblies\\Assembly-CSharp-firstpass.dll",
        ]
    }
```

I guess should mention this within the repository.

Then the linter should work, if not then check the Sublime Text console(Ctrl + ~).

**Comment by jasjuang** [comment]
I found gmcs.bat and the folder of where it is located at to the PATH variable

now I am getting these error in the Sublime Text console

```
File "linter in C:\Users\jasju\AppData\Roaming\Sublime Text 3\Installed Packages\SublimeLinter-contrib-csharplint.sublime-package", line 90, in cmd
  File "linter in C:\Users\jasju\AppData\Roaming\Sublime Text 3\Installed Packages\SublimeLinter-contrib-csharplint.sublime-package", line 121, in get_setting
AttributeError: 'Csharplint' object has no attribute 'get_settings'
```

I usually don't use projects for sublime, I just open individual files. Is there any way to make this work without having to have a project?

**Comment by Pendrokar** [comment]
There is a way, replace **self.get_setting("completesharp_assemblies", [])** with an array([]) that includes all the mentioned libraries. The last four libraries will also have to have absolute paths as those project_path variables will not work.

**Comment by jasjuang** [comment]
I tried forking the repo https://github.com/jasjuang/SublimeLinter-contrib-csharplint and edit the linter.py file as you mentioned. But then I realized I do not have Assembly-UnityScript.dll on my unity. So I just added everything except that. And I am getting the below errors

```
SublimeLinter: error in SublimeLinter daemon: 
SublimeLinter: -------------------- 
SublimeLinter: Traceback (most recent call last):
  File "C:\Users\jasju\AppData\Roaming\Sublime Text 3\Packages\SublimeLinter\lint\queue.py", line 57, in loop
    item = self.q.get(block=True, timeout=self.MIN_DELAY)
  File "./queue.py", line 175, in get
queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\jasju\AppData\Roaming\Sublime Text 3\Packages\SublimeLinter\lint\queue.py", line 65, in loop
    self.lint(view_id, timestamp)
  File "C:\Users\jasju\AppData\Roaming\Sublime Text 3\Packages\SublimeLinter\lint\queue.py", line 111, in lint
    self.callback(view_id, timestamp)
  File "C:\Users\jasju\AppData\Roaming\Sublime Text 3\Packages\SublimeLinter\sublimelinter.py", line 119, in lint
    Linter.lint_view(view, filename, code, hit_time, callback)
  File "C:\Users\jasju\AppData\Roaming\Sublime Text 3\Packages\SublimeLinter\lint\linter.py", line 929, in lint_view
    linter.lint(hit_time)
  File "C:\Users\jasju\AppData\Roaming\Sublime Text 3\Packages\SublimeLinter\lint\linter.py", line 1388, in lint
    cmd = self.get_cmd()
  File "C:\Users\jasju\AppData\Roaming\Sublime Text 3\Packages\SublimeLinter\lint\linter.py", line 1117, in get_cmd
    cmd = self.cmd()
  File "linter in C:\Users\jasju\AppData\Roaming\Sublime Text 3\Installed Packages\SublimeLinter-contrib-csharplint.sublime-package", line 110, in cmd
  File "linter in C:\Users\jasju\AppData\Roaming\Sublime Text 3\Installed Packages\SublimeLinter-contrib-csharplint.sublime-package", line 143, in get_setting
AttributeError: 'Csharplint' object has no attribute 'get_settings'

SublimeLinter: -------------------- 
```

Please advice, thanks!

**Comment by Pendrokar** [comment]
"AttributeError: 'Csharplint' object has no attribute 'get_settings'"
This error tells me you still haven't replaced the line I mentioned, just remove the function and leave the array([...]). "Assembly-UnityScript.dll" and the three others are created by Unity within the Unity project's Library folder.

**Comment by jasjuang** [comment]
I think I misunderstood what you meant before and now I added a new commit that should reflect the replacement. However, I am getting an new error

```
SublimeLinter: ERROR: could not launch ['mcs', '-target:library', '-out:/tmp/errorcheck.dll', '-r:C:/Program Files/Unity/Editor/Data/Managed/UnityEngine.dll,C:/Program Files/Unity/Editor/Data/Managed/UnityEditor.dll,C:/Program Files/Unity/Editor/Data/Mono/lib/mono/unity/UnityScript.dll,C:/Program Files/Unity/Editor/Data/Mono/lib/mono/unity/System.Core.dll,C:/Program Files/Unity/Editor/Data/Mono/lib/mono/unity/System.dll,C:/Program Files/Unity/Editor/Data/Managed/nunit.framework.dll,C:/Program Files/Unity/Editor/Data/Mono/lib/mono/unity/mscorlib.dll,C:/Users/Public/Documents/Unity Projects/Standard Assets Example Project/Library/ScriptAssemblies/Assembly-CSharp.dll,C:/Users/Public/Documents/Unity Projects/Standard Assets Example Project/Library/ScriptAssemblies/Assembly-CSharp-Editor.dll,C:/Users/Public/Documents/Unity Projects/Standard Assets Example Project/Library/ScriptAssemblies/Assembly-CSharp-firstpass.dll', '-nostdlib', 'c:\\users\\jasju\\appdata\\local\\temp\\SublimeLinter3-jasju\\login.cs'] 
SublimeLinter: reason: [WinError 2] The system cannot find the file specified 
```

Do you know what could be the problem? Thanks so much for your patience

**Comment by Pendrokar** [comment]
It probably can't find mcs command, just set your 'base_cmd' the same way I did in a previous comment:
https://github.com/Pendrokar/SublimeLinter-contrib-csharplint/issues/3#issuecomment-217562097

**Comment by jasjuang** [comment]
I changed it based on your comment #3, please check my fork if I am doing it right.

When I type gmcs test.cs in the command line, I get the following output

```
test.cs(1,7): error CS0246: The type or namespace name `UnityEngine' could not be found. Are you missing a using directive or an assembly reference?
```

At least that means gmcs is in the PATH variable. However in the sublime console I am still getting

```
SublimeLinter: ERROR: could not launch ['gmcs', '-target:library', '-r:C:/Program Files/Unity/Editor/Data/Managed/UnityEngine.dll,C:/Program Files/Unity/Editor/Data/Managed/UnityEditor.dll,C:/Program Files/Unity/Editor/Data/Mono/lib/mono/unity/UnityScript.dll,C:/Program Files/Unity/Editor/Data/Mono/lib/mono/unity/System.Core.dll,C:/Program Files/Unity/Editor/Data/Mono/lib/mono/unity/System.dll,C:/Program Files/Unity/Editor/Data/Managed/nunit.framework.dll,C:/Program Files/Unity/Editor/Data/Mono/lib/mono/unity/mscorlib.dll,C:/Users/Public/Documents/Unity Projects/Standard Assets Example Project/Library/ScriptAssemblies/Assembly-CSharp.dll,C:/Users/Public/Documents/Unity Projects/Standard Assets Example Project/Library/ScriptAssemblies/Assembly-CSharp-Editor.dll,C:/Users/Public/Documents/Unity Projects/Standard Assets Example Project/Library/ScriptAssemblies/Assembly-CSharp-firstpass.dll', '-nostdlib', 'c:\\users\\jasju\\appdata\\local\\temp\\SublimeLinter3-jasju\\video.cs'] 
```

What am I doing wrong?

**Comment by Pendrokar** [comment]
Hmm, not sure. I also have everything in their default paths. The only differences we have is that I use the full path to gmcs. This is what I am seeing:

```
SublimeLinter: csharplint: KnockdownForce.cs ['C:/Program Files/Unity/Editor/Data/Mono/bin/gmcs.bat', '-target:library', '-r:C:/Program Files/Unity/Editor/Data/Managed/UnityEngine.dll,C:/Program Files/Unity/Editor/Data/Managed/UnityEditor.dll,C:/Program Files/Unity/Editor/Data/Mono/lib/mono/unity/UnityScript.dll,C:/Program Files/Unity/Editor/Data/Mono/lib/mono/unity/System.Core.dll,C:/Program Files/Unity/Editor/Data/Mono/lib/mono/unity/System.dll,C:/Program Files/Unity/Editor/Data/Managed/nunit.framework.dll,C:/Program Files/Unity/Editor/Data/Mono/lib/mono/unity/mscorlib.dll,C:/Users/Janis/Documents/Telezerk/Library/ScriptAssemblies/Assembly-CSharp.dll,C:/Users/Janis/Documents/Telezerk/Library/ScriptAssemblies/Assembly-CSharp-Editor.dll,C:/Users/Janis/Documents/Telezerk/Library/ScriptAssemblies/Assembly-UnityScript.dll,C:/Users/Janis/Documents/Telezerk/Library/ScriptAssemblies/Assembly-CSharp-firstpass.dll', '-nostdlib'] 
```

**Comment by jasjuang** [comment]
I finally get it to work with the full PATH, without the full PATH it seems that gmcs.exe is invoked instead of gmcs,bat. Thanks again for your help.

Would you consider putting this in package control? So whoever is using it won't need to add the repo in order to use it.

Would it be possible to overwrite base_cmd and and extra in some type of package settings? So whoever is using it won't need to fork the repo in order to change the linter.py file.

**Comment by hsandt** [comment]
Hi! I followed Pendrokar's instructions but I had to:
- replace `self.get_settings` with `self.get_view_settings` in csharplint's `linter.py` to leverage the base class Linter's own settings loader
- Complete the csharplint settings in `SublimeLinter.sublime-settings`:

```
"csharplint": {
    "@disable": false,
    "args": [],
    "excludes": [],
    "filter": "",
    "completesharp_assemblies": [
        "C:\\Program Files\\Unity\\Editor\\Data\\Managed\\UnityEngine.dll",
        "C:\\Program Files\\Unity\\Editor\\Data\\Managed\\UnityEditor.dll",
        "C:\\Program Files\\Unity\\Editor\\Data\\Mono\\lib\\mono\\unity\\UnityScript.dll",
        "C:\\Program Files\\Unity\\Editor\\Data\\Mono\\lib\\mono\\unity\\System.Core.dll",
        "C:\\Program Files\\Unity\\Editor\\Data\\Mono\\lib\\mono\\unity\\System.dll",
        "C:\\Program Files\\Unity\\Editor\\Data\\Managed\\nunit.framework.dll",
        "C:\\Program Files\\Unity\\Editor\\Data\\Mono\\lib\\mono\\unity\\mscorlib.dll",
        "${project}\\Library\\ScriptAssemblies\\Assembly-CSharp.dll",
        "${project}\\Library\\ScriptAssemblies\\Assembly-CSharp-Editor.dll",
        "${project}\\Library\\ScriptAssemblies\\Assembly-UnityScript.dll",
        "${project}\\Library\\ScriptAssemblies\\Assembly-CSharp-firstpass.dll"
    ],
}
```

(note ${project}\Library instead of ${project_path:Library})
You'll need to adapt to your OS of course.

Alternatively, you may use `sublime.load_settings(package_name)` to use the classic which is what Pendrokar seems to be doing, but I haven't tried yet as I wasn't sure if `package_name` was important and what to type exactly. If you go this way, use Sublime Text's own User preferences.

Linting works, although the linter has hard time guessing which namespace is used (resulting in spotting conflicts when there are none) and cannot find my custom extensions.
